### PR TITLE
Try enabling the Windows build

### PR DESCRIPTION
**Pull request by inducer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by inducer** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
No dice:
```
 fatal error C1047: The object or library file 'D:\bld\pymetis_1598210960501\_h_env\Library\lib\metis.lib' was created with an older compiler than other objects; rebuild old objects and libraries
    LINK : fatal error LNK1257: code generation failed
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe' failed with exit status 1257
    Running setup.py install for PyMetis: finished with status 'error'
```

cc @isuruf (only if you're interested, I only care so much)

**Comment by isuruf** [comment]
Should be fixed in https://github.com/conda-forge/metis-feedstock/pull/29

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
